export const serviceQueryFields=`{
    data{
      id
      attributes
      {
        name
              long_desc
              short_desc
              code
              provider_id
              {
                data{
                  id
                  attributes
                  {
                    provider_id
                    provider_uri
                    provider_name
                    short_desc
                    long_desc
                    domain_id{
                      data
                      {
                        id
                        attributes
                        {
                          DomainName
                        }
                      }
                      
                    }
                    location_id{
                      data{
                        id
                        attributes
                        {
                          address
                          city
                          state
                          country
                          zip
                        }
                      }
                    }
                    logo{
                      data{
                        id
                        attributes
                        {url}
                      }
                    }
              
                    
                  }
                }
              }
        		service
        {
          data
          {
            id
            attributes
            {
              
              agent_id{
        data{
          id
          attributes
          {
            first_name
            last_name
            years_experience
            description
            agent_profile
            {
              data
              {
                id
                attributes
                {
                  qualification
                  institute
                  passing_year
                }
              }
            }
            locations
            {
              data
              {
                id
                attributes
                {
                  address
                  city
                  state
                  country
                  zip
                }
              }
            }
            
          }
        }
      }
      time_slot_per_client_in_min
      service_fee
      followup_service_fee
      location_id
      {
        data{
          id
          attributes
          {
            address
            state
            city
            country
            zip
          }
        }
      }
              service_availabilities
      {
        data
        {
          id
          attributes
          {
            start_time
            end_time
            is_available
            day_of_week
            unavailability_reason
            
          }
        }
      }
              
            }
          }
        }
         
              
      }
    }
  }`
 export const serviceQueryTable="items"