export const fulfillmentQueryFields = ` {
  data
  {
    id
    attributes
    {
      fulfilment_id
      {
        data
        {
          id
        }
        
      }
      state_code
      state_value
      customer_id
      {
        data
        {
          id
          attributes
          {
            first_name
            email
            contact
          }
        }
      }
      agent_id
      {
        data
        {
          id
          attributes
          {
            first_name
            agent_fees
          }
        }
      }
      order_fulfillment_location_id
      {
        data
        {
          id
          attributes
          {
            gps
            address
            state_code
            state_name
            city_name
            city_code
            country_name
            country_code
            area_code
          }
        }
      }
      order_id
      {
        data
        {
          id
          attributes
          {
            order_address
            {
              data
              {
                id
                attributes
                {
                  first_name
                  address_type
                  address_line_1
                  address_line_1
                  tax_id
                  city
                  country
                  postcode
                  state
                  email
                  phone
                }
              }
            }
          }
        }
      }
    }
  }
}`;
export const fulfillmentQueryTable = "orderFulfillments";
